language : csharp
dist: trusty
sudo: enabled
dotnet : 2.0.0
services:
 - docker
before_install:
 - chmod +x ./deploy.sh
script:
- dotnet build 
after_success:
- dotnet publish
deploy:
  provider: script
  script: sh deploy.sh
 